import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:pubspec_parse/pubspec_parse.dart';

import '../core/issue.dart';
import '../graph/module_graph.dart';
import 'detector.dart';

/// Detects unused packages listed in pubspec.yaml.
class UnusedDepDetector implements Detector {
  const UnusedDepDetector({required this.projectRoot});

  final String projectRoot;

  @override
  List<Issue> detect({
    required Set<String> projectFiles,
    required Set<String> entryFiles,
    required ModuleGraph graph,
    required Map<IssueType, Severity> rules,
    required List<String> ignoreDependencies,
  }) {
    final depSeverity = rules[IssueType.unusedDependency];

    if (_isDisabled(depSeverity)) {
      return const [];
    }

    final pubspecFile = File(p.join(projectRoot, 'pubspec.yaml'));
    if (!pubspecFile.existsSync()) return const [];

    final pubspec = Pubspec.parse(pubspecFile.readAsStringSync());
    final usedPackages = graph.externalPackageUsage.keys.toSet();
    final ignoredSet = ignoreDependencies.toSet();

    // Collect dependencies that are transitively required by used packages.
    final transitivelyUsed = _collectTransitiveDeps(pubspec, usedPackages);
    usedPackages.addAll(transitivelyUsed);

    return _checkDeps(
      deps: pubspec.dependencies.keys,
      type: IssueType.unusedDependency,
      severity: depSeverity,
      label: 'Unused dependency',
      usedPackages: usedPackages,
      ignoredSet: ignoredSet,
    );
  }

  static bool _isDisabled(Severity? severity) =>
      severity == null || severity == Severity.off;

  /// Collect packages that are transitively required by used packages.
  ///
  /// Uses multiple strategies to resolve the full dependency graph:
  /// 1. Parse `.dart_tool/package_graph.json` if available (build_runner)
  /// 2. Use `.dart_tool/package_config.json` to locate packages and read
  ///    their pubspec.yaml (standard Dart tooling)
  /// 3. Fall back to walking path dependencies only
  Set<String> _collectTransitiveDeps(
    Pubspec pubspec,
    Set<String> usedPackages,
  ) {
    final packageName = pubspec.name;

    // Strategy 1: Use package_graph.json (generated by build_runner).
    final graphResult = _collectFromPackageGraph(packageName, usedPackages);
    if (graphResult != null) return graphResult;

    // Strategy 2: Use package_config.json (standard Dart tooling).
    final configResult =
        _collectFromPackageConfig(packageName, usedPackages);
    if (configResult != null) return configResult;

    // Strategy 3: Walk path dependencies only (minimal fallback).
    return _collectFromPathDeps(pubspec, usedPackages);
  }

  /// Parse `.dart_tool/package_graph.json` and compute transitive closure
  /// of used packages.
  Set<String>? _collectFromPackageGraph(
    String packageName,
    Set<String> usedPackages,
  ) {
    final graphFile = File(
      p.join(projectRoot, '.dart_tool', 'package_graph.json'),
    );
    if (!graphFile.existsSync()) return null;

    try {
      final json =
          jsonDecode(graphFile.readAsStringSync()) as Map<String, dynamic>;
      final packages = json['packages'] as List<dynamic>;

      // Verify this graph belongs to the current project.
      if (!packages.any(
        (pkg) => (pkg as Map<String, dynamic>)['name'] == packageName,
      )) {
        return null;
      }

      final depGraph = <String, List<String>>{};
      for (final pkg in packages) {
        final map = pkg as Map<String, dynamic>;
        final name = map['name'] as String;
        final deps =
            (map['dependencies'] as List<dynamic>?)?.cast<String>() ??
            const <String>[];
        depGraph[name] = deps;
      }

      return _transitiveClosureOf(usedPackages, depGraph);
    } on Object {
      return null;
    }
  }

  /// Find `.dart_tool/package_config.json` by searching upward from
  /// [projectRoot], resolve package paths, read their pubspec.yaml files,
  /// and compute transitive closure.
  Set<String>? _collectFromPackageConfig(
    String packageName,
    Set<String> usedPackages,
  ) {
    final configFile = _findPackageConfig();
    if (configFile == null) return null;

    try {
      final json =
          jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
      final packages = json['packages'] as List<dynamic>;

      // Verify this config belongs to the current project.
      if (!packages.any(
        (pkg) => (pkg as Map<String, dynamic>)['name'] == packageName,
      )) {
        return null;
      }

      final configDir = p.dirname(configFile.path);

      // Map package name → root path on disk.
      final packagePaths = <String, String>{};
      for (final pkg in packages) {
        final map = pkg as Map<String, dynamic>;
        final name = map['name'] as String;
        final rootUri = map['rootUri'] as String;
        if (rootUri.startsWith('file://')) {
          packagePaths[name] = Uri.parse(rootUri).toFilePath();
        } else {
          // Relative URI: resolve relative to the directory containing
          // package_config.json (i.e. .dart_tool/).
          packagePaths[name] = p.normalize(p.join(configDir, rootUri));
        }
      }

      // Build dependency graph by reading each package's pubspec.yaml.
      final depGraph = <String, List<String>>{};
      final visited = <String>{};

      void resolvePackage(String name) {
        if (!visited.add(name)) return;
        final rootPath = packagePaths[name];
        if (rootPath == null) return;

        final pubspecFile = File(p.join(rootPath, 'pubspec.yaml'));
        if (!pubspecFile.existsSync()) return;

        try {
          final pubspec = Pubspec.parse(pubspecFile.readAsStringSync());
          final deps = pubspec.dependencies.keys.toList();
          depGraph[name] = deps;
          for (final dep in deps) {
            resolvePackage(dep);
          }
        } on Object {
          // Skip unparseable pubspec files.
        }
      }

      for (final name in usedPackages) {
        resolvePackage(name);
      }

      return _transitiveClosureOf(usedPackages, depGraph);
    } on Object {
      return null;
    }
  }

  /// Search upward from [projectRoot] for `.dart_tool/package_config.json`.
  File? _findPackageConfig() {
    var dir = Directory(projectRoot);
    for (var i = 0; i < 10; i++) {
      final configFile = File(
        p.join(dir.path, '.dart_tool', 'package_config.json'),
      );
      if (configFile.existsSync()) return configFile;
      final parent = dir.parent;
      if (parent.path == dir.path) return null;
      dir = parent;
    }
    return null;
  }

  /// Compute the set of all packages transitively reachable from [seeds]
  /// in the given [depGraph].
  static Set<String> _transitiveClosureOf(
    Set<String> seeds,
    Map<String, List<String>> depGraph,
  ) {
    final transitive = <String>{};
    final visited = <String>{};

    void walk(String name) {
      if (!visited.add(name)) return;
      final deps = depGraph[name];
      if (deps == null) return;
      for (final dep in deps) {
        transitive.add(dep);
        walk(dep);
      }
    }

    for (final seed in seeds) {
      walk(seed);
    }
    return transitive;
  }

  /// Walk path dependencies only (minimal fallback when no package
  /// resolution files are available).
  Set<String> _collectFromPathDeps(
    Pubspec pubspec,
    Set<String> usedPackages,
  ) {
    final transitive = <String>{};
    final visited = <String>{};

    void walk(String depName, Dependency dep) {
      if (!visited.add(depName)) return;
      if (dep is! PathDependency) return;

      final depPubspecFile = File(
        p.join(projectRoot, dep.path, 'pubspec.yaml'),
      );
      if (!depPubspecFile.existsSync()) return;

      try {
        final depPubspec = Pubspec.parse(depPubspecFile.readAsStringSync());
        for (final entry in depPubspec.dependencies.entries) {
          transitive.add(entry.key);
          walk(entry.key, entry.value);
        }
      } on Object {
        // Skip unparseable pubspec files.
      }
    }

    for (final entry in pubspec.dependencies.entries) {
      if (usedPackages.contains(entry.key) || entry.value is PathDependency) {
        walk(entry.key, entry.value);
      }
    }

    return transitive;
  }

  /// Platform suffixes for Flutter Federated Plugin endorsement packages.
  static const _platformSuffixes = [
    '_ios',
    '_android',
    '_web',
    '_linux',
    '_macos',
    '_windows',
  ];

  /// Check if [dep] is a platform endorsement package whose parent
  /// package is used or explicitly listed in dependencies.
  static bool _isPlatformEndorsement(
    String dep,
    Set<String> usedPackages,
    Set<String> allDeps,
  ) {
    for (final suffix in _platformSuffixes) {
      if (dep.endsWith(suffix)) {
        final parent = dep.substring(0, dep.length - suffix.length);
        if (usedPackages.contains(parent) || allDeps.contains(parent)) {
          return true;
        }
      }
    }
    return false;
  }

  List<Issue> _checkDeps({
    required Iterable<String> deps,
    required IssueType type,
    required Severity? severity,
    required String label,
    required Set<String> usedPackages,
    required Set<String> ignoredSet,
  }) {
    if (_isDisabled(severity)) return const [];

    final allDeps = deps.toSet();

    return [
      for (final dep in deps)
        if (!ignoredSet.contains(dep) &&
            !usedPackages.contains(dep) &&
            !_isPlatformEndorsement(dep, usedPackages, allDeps))
          Issue(
            type: type,
            severity: severity!,
            filePath: 'pubspec.yaml',
            symbol: dep,
            message: '$label: $dep',
          ),
    ];
  }
}
